observability:
  opentelemetry:
    enable_metrics: true
    file: 
      path: ./go_output.txt
    apmplus:
      endpoint: "http://apmplus-cn-beijing.volces.com:4317"
      api_key: ""
      service_name: "veadk.go.demo"
    
