name: pre_check.yml
on:
  push:
    branches: [ "main", "develop" ]
    paths: [ "**.go", "go.mod", "go.sum" ]
  pull_request:
    branches: [ "main", "develop" ]
    paths: [ "**.go", "go.mod", "go.sum" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          install-mode: goinstall
          version: latest
          args: --timeout=10m

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Tidy
        run: go mod tidy -diff

      - name: Build
        run: go build -mod=readonly -v ./...

      - name: Run unit tests
        run: |
          go test -mod=readonly -v -race -count=1 -shuffle=on \
            -coverprofile=coverage.out -covermode=atomic \
            ./...

